# Generated by Django 6.0 on 2025-12-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='img/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
