# Generated by Django 6.0 on 2025-12-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
