# Generated by Django 6.0 on 2025-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_alter_post_img_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Видео (Google Drive)'),
        ),
    ]
