# Generated by Django 6.0 on 2025-12-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_description_remove_post_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faq_for',
            field=models.ForeignKey(blank=True, help_text='Если это FAQ — выбери статью, к которой он относится', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.post', verbose_name='FAQ для статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
